---
- name: Renmove all packages installed for PCS cluster
  hosts: samba_servers
  gather_facts: no
  tasks:

    - name: Delete GFS2FS
      command: 'pcs resource delete gfs2fs'
      ignore_errors: True
      run_once: True

    - name: Check for LV
      command: 'lvs'
      ignore_errors: True
      register: result

    - name: Remove Clusterd Logical Vol
      lvol: 
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        state: absent
        force: yes
      run_once: True
      when: result.stdout.find('lvcluster') != -1
      notify:
        - reboot_servers

    - name: Check for VG
      command: 'vgs'
      ignore_errors: True
      register: result


    - name: Remove Clusteres Volume Group
      lvg:
        vg: "{{ vg_name }}"
        state: absent
        force: Yes
      run_once: True
      when: result.stdout.find('vgclvm') != -1
      notify:
        - reboot_servers

    - name: Delete resources
      command: 'pcs resource delete {{ item }}'
      ignore_errors: True
      run_once: True
      loop:
        #- fip
        - '{{ clvmd_name }}-clone'
        - '{{ dlm_name }}-clone'
      notify:
        - reboot_servers

    - name: Destroy cluster
      command: 'pcs cluster destroy'
      ignore_errors: yes
      register: result
      notify:
        - reboot_servers

    - name: Print the Result
      debug:
        var: result

    - name: Unistall PCS packages
      yum:
        name: "{{ packages }}"
        state: absent
      notify:
        - reboot_servers
      
    - name: Remove tokens file if found
      file:
        path: "{{ tokens_file }}"
        state: absent
    - name: Remove Corosync configuration file if found
      file:
        path: "{{ corosync_conf }}"
        state: absent

    - name: Remove clusterfs directory
      file:
        path: "{{ gfs2_mount_point }}"
        state: absent


    - name: Complete pending Yum transactions
      command: 'yum-complete-transaction --cleanup-only'
      

  handlers:
    - name: reboot_servers
      reboot: 
