---
- name: Sync Pull task - Executed on  the Destination host "{{groups['samba_servers_dr'][0]}}"
  hosts: "{{groups['samba_servers_main'][1]}}"
  gather_facts: False
  tasks:   
    - name: Pull data from Main site to DR site
      synchronize:
        src: "{{ item }}"
        dest: "/clusterfs"
        mode: pull
        recursive: yes
        delete: yes
        group: yes
        links: yes
        owner: yes
        perms: yes
        times: yes
        rsync_opts:
          - "--executability"
          - "--acls"
          - "--xattrs"
      delegate_to: "{{groups['samba_servers_dr'][0]}}"
      run_once: true
      with_items:
        - "/clusterfs/share"
        - "/clusterfs/home"
