---
- name: Create share directories, define ACLs and update Samba configuration.
  hosts: samba_servers_main
  gather_facts: false
  vars_files:
    - vars/main.yaml
    - vars/samba.yaml

  tasks:
  - name: Create Directories
    file:
      path: "{{ gfs2_mount_point }}/share/{{ item.path }}"
      state: directory
      owner: root
      group: root
      mode: '{{ item.mode }}'
    with_items:
      - "{{ samba_shares }}"

  - name: Define ACLs
    acl:
      path: "{{ gfs2_mount_point }}/share/{{ item.0.path }}"
      entry: "{{ item.1 }}"
      state: present
    with_subelements:
      - "{{ samba_shares }}"
      - acls
    when: not item.0.hidden

  - name: Samba Config
    template:
      src: templates/smb.conf.j2
      dest: /etc/samba/smb.conf


- name: Update DR Samba configuration
  hosts: samba_servers_dr
  gather_facts: false
  vars_files:
    - vars/samba.yaml
    - vars/main.yaml
  tasks:
  - name: Update Samba Config
    template:
      src: templates/smb.conf.dr.j2
      dest: /etc/samba/smb.conf
